/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        CharStream input = CharStreams.fromString(code);

        DSLLexer lexer = new DSLLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);

        DSLParser parser = new DSLParser(tokens);
        // ESTO genera el parse tree
        ParseTree tree = parser.program();

    }
}
