/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import javax.swing.JTextArea;

/**
 *
 * @author Alexis Martinez
 */
public class BottomInfo extends javax.swing.JPanel {

    /**
     * Creates new form BottomInfo
     */
    public BottomInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_output_console = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlConsoleOutput();
        pnl_operations = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlOperations();

        setLayout(new java.awt.GridLayout(1, 2, 15, 15));

        pnl_output_console.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        pnl_output_console.setName(""); // NOI18N
        pnl_output_console.setPreferredSize(new java.awt.Dimension(274, 40));
        add(pnl_output_console);

        pnl_operations.setMaximumSize(new java.awt.Dimension(40, 40));
        pnl_operations.setMinimumSize(new java.awt.Dimension(20, 10));
        pnl_operations.setPreferredSize(new java.awt.Dimension(105, 40));
        add(pnl_operations);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alexis.martinez.trabajo.hdltranspiler.ui.PnlOperations pnl_operations;
    private com.alexis.martinez.trabajo.hdltranspiler.ui.PnlConsoleOutput pnl_output_console;
    // End of variables declaration//GEN-END:variables

    JTextArea getTextAreaOutputConsole() {
        return pnl_output_console.getTextAreaOutput();
    }

    void reset() {
        pnl_output_console.clear();
    }
}
