/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import javax.swing.JTextArea;

/**
 *
 * @author Alexis Martinez
 */
public class PnlConsoleOutput extends javax.swing.JPanel {

    /**
     * Creates new form Output
     */
    public PnlConsoleOutput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_console_output = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_output = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(97, 68));
        setLayout(new java.awt.BorderLayout());

        lbl_console_output.setText("Console output");
        add(lbl_console_output, java.awt.BorderLayout.PAGE_START);

        txt_area_output.setEditable(false);
        txt_area_output.setColumns(2);
        txt_area_output.setRows(2);
        txt_area_output.setToolTipText("");
        txt_area_output.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_area_output.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jScrollPane1.setViewportView(txt_area_output);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_console_output;
    private javax.swing.JTextArea txt_area_output;
    // End of variables declaration//GEN-END:variables

    JTextArea getTextAreaOutput() {
        return txt_area_output;
    }
    
    void clear() {
        txt_area_output.setText("");
    }
}
