/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

/**
 *
 * @author u0_a525
 */
public class PnlGridMain extends javax.swing.JPanel {

    /**
     * Creates new form pnlGridMain
     */
    public PnlGridMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_RTL_input1 = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlRTLInput();
        pnl_system_verilog_output = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlSystemVerilogOutput();
        pnl_output_console = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlConsoleOutput();
        pnl_operations = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlOperations();

        setLayout(new java.awt.GridLayout(2, 2));
        add(pnl_RTL_input1);
        add(pnl_system_verilog_output);
        add(pnl_output_console);
        add(pnl_operations);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.alexis.martinez.trabajo.hdltranspiler.ui.PnlRTLInput pnl_RTL_input1;
    public com.alexis.martinez.trabajo.hdltranspiler.ui.PnlOperations pnl_operations;
    public com.alexis.martinez.trabajo.hdltranspiler.ui.PnlConsoleOutput pnl_output_console;
    public com.alexis.martinez.trabajo.hdltranspiler.ui.PnlSystemVerilogOutput pnl_system_verilog_output;
    // End of variables declaration//GEN-END:variables
}
