/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

/**
 *
 * @author Alexis Martinez
 */
public class PnlGridMain extends javax.swing.JPanel {

    /**
     * Creates new form pnlGridMain
     */
    public PnlGridMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottomInfo1 = new com.alexis.martinez.trabajo.hdltranspiler.ui.BottomInfo();
        jPanel1 = new javax.swing.JPanel();
        pnl_RTL_input1 = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlRTLInput();
        pnl_system_verilog_output = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlSystemVerilogOutput();

        setLayout(new java.awt.BorderLayout(15, 15));

        bottomInfo1.setMinimumSize(new java.awt.Dimension(209, 10));
        bottomInfo1.setOpaque(false);
        bottomInfo1.setPreferredSize(new java.awt.Dimension(225, 80));
        add(bottomInfo1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 15, 15));
        jPanel1.add(pnl_RTL_input1);
        jPanel1.add(pnl_system_verilog_output);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alexis.martinez.trabajo.hdltranspiler.ui.BottomInfo bottomInfo1;
    private javax.swing.JPanel jPanel1;
    private com.alexis.martinez.trabajo.hdltranspiler.ui.PnlRTLInput pnl_RTL_input1;
    private com.alexis.martinez.trabajo.hdltranspiler.ui.PnlSystemVerilogOutput pnl_system_verilog_output;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextArea getConsoleOutputComponent() {
        return bottomInfo1.getTextAreaOutputConsole();
    }

    public void setSystemVerilogOutput(String text) {
        this.pnl_system_verilog_output.getTextAreaOutputSV().setText(text);
        this.pnl_system_verilog_output.getTextAreaOutputSV().setCaretPosition(0);
    }

    public void setVerilogOutput(String text) {
        this.pnl_system_verilog_output.getTextAreaOutputV().setText(text);
        this.pnl_system_verilog_output.getTextAreaOutputV().setCaretPosition(0);
    }

    public void setRTLInput(String text) {
        pnl_RTL_input1.setInputRTL(text);
    }

    public String getInputRTLValue() {
        return this.pnl_RTL_input1.getInputRTLValue();
    }

    public void setConsoleOutput(String value) {
        this.bottomInfo1.getTextAreaOutputConsole().setText(value);
    }

    public void reset_history() {
        this.pnl_RTL_input1.reset_history();
    }

    public void reset() {
        this.pnl_RTL_input1.reset();
        this.bottomInfo1.reset();
        this.pnl_system_verilog_output.reset();
    }

    void setLblFile(String value) {
        pnl_RTL_input1.setLblFile(value);
    }

    public boolean get_input_changed() {
        return this.pnl_RTL_input1.get_input_changed();
    }

    public void resetWasEdited() {
        this.pnl_RTL_input1.resetWasEdited();
    }

    void undo() {
        this.pnl_RTL_input1.undo();
    }

    void redo() {
        this.pnl_RTL_input1.redo();
    }

    void on_save() {
        this.pnl_RTL_input1.on_save();
    }
}
