/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.HdlTranspiler;
import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.hdl_to_sv.HdlToSV;
import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.sv_to_v.SystemVerilogToVerilog;

/**
 *
 * @author Alexis Martinez
 */
public class PnlOperations extends javax.swing.JPanel {

    /**
     * Creates new form pnl_Operations
     */
    public PnlOperations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_show_graph_hdl_sv = new javax.swing.JButton();
        btn_show_graph_sv_to_v = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 40));
        setPreferredSize(new java.awt.Dimension(105, 68));
        setLayout(new java.awt.GridLayout(1, 0));

        btn_show_graph_hdl_sv.setText("Show graph hdl to sv");
        btn_show_graph_hdl_sv.setToolTipText("");
        btn_show_graph_hdl_sv.setMaximumSize(new java.awt.Dimension(32314, 413431));
        btn_show_graph_hdl_sv.setMinimumSize(new java.awt.Dimension(105, 10));
        btn_show_graph_hdl_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_graph_hdl_svActionPerformed(evt);
            }
        });
        add(btn_show_graph_hdl_sv);

        btn_show_graph_sv_to_v.setText("Show graph sv to v");
        btn_show_graph_sv_to_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_graph_sv_to_vActionPerformed(evt);
            }
        });
        add(btn_show_graph_sv_to_v);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_show_graph_hdl_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_graph_hdl_svActionPerformed
        HdlToSV.visualize();
    }//GEN-LAST:event_btn_show_graph_hdl_svActionPerformed

    private void btn_show_graph_sv_to_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_graph_sv_to_vActionPerformed
        SystemVerilogToVerilog.visualize();
    }//GEN-LAST:event_btn_show_graph_sv_to_vActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_show_graph_hdl_sv;
    private javax.swing.JButton btn_show_graph_sv_to_v;
    // End of variables declaration//GEN-END:variables
}
