/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.HdlTranspiler;
import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.hdl_to_sv.HdlToSV;

/**
 *
 * @author Alexis Martinez
 */
public class PnlOperations extends javax.swing.JPanel {

    /**
     * Creates new form pnl_Operations
     */
    public PnlOperations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_show_graph = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 40));
        setPreferredSize(new java.awt.Dimension(105, 68));
        setLayout(new java.awt.GridLayout(1, 0));

        btn_show_graph.setText("Show graph");
        btn_show_graph.setToolTipText("");
        btn_show_graph.setMaximumSize(new java.awt.Dimension(32314, 413431));
        btn_show_graph.setMinimumSize(new java.awt.Dimension(105, 10));
        btn_show_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_graphActionPerformed(evt);
            }
        });
        add(btn_show_graph);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_show_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_graphActionPerformed
        HdlToSV.visualize();
    }//GEN-LAST:event_btn_show_graphActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_show_graph;
    // End of variables declaration//GEN-END:variables
}
