/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexis Martinez
 */
public class PnlRTLInput extends javax.swing.JPanel {

    /**
     * Creates new form RTL_input
     */
    public PnlRTLInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_rtl_description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_rtl = new javax.swing.JTextArea();
        btn_example = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lbl_rtl_description.setText("RTL description");
        lbl_rtl_description.setToolTipText("");
        add(lbl_rtl_description, java.awt.BorderLayout.PAGE_START);

        input_rtl.setColumns(20);
        input_rtl.setRows(5);
        input_rtl.setTabSize(2);
        input_rtl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_rtl.setOpaque(false);
        jScrollPane1.setViewportView(input_rtl);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btn_example.setText("Example !");
        btn_example.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exampleActionPerformed(evt);
            }
        });
        add(btn_example, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exampleActionPerformed

        InputStream is = getClass().getResourceAsStream("/examples/RTL_tick_led.hdl");
        try {
            String example_content = new String(is.readAllBytes(), StandardCharsets.UTF_8);

            this.input_rtl.setText(example_content);

        } catch (IOException ex) {
            Logger.getLogger(PnlRTLInput.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_exampleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_example;
    public javax.swing.JTextArea input_rtl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_rtl_description;
    // End of variables declaration//GEN-END:variables
}
