/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import com.alexis.martinez.trabajo.hdltranspiler.ui.control.ExampleGenerator;
import com.alexis.martinez.trabajo.hdltranspiler.ui.file.History;

/**
 *
 * @author Alexis Martinez
 */
public class PnlRTLInput extends javax.swing.JPanel {

    private final History history;

    /**
     * Creates new form RTL_input
     */
    public PnlRTLInput() {
        initComponents();
        this.history = new History();
        this.reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _txt_input_rtl = new javax.swing.JEditorPane();
        lbl_title = new javax.swing.JLabel();
        btn_example = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_input_rtl = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        lbl_title.setText("<Not saved>");
        lbl_title.setToolTipText("");
        add(lbl_title, java.awt.BorderLayout.PAGE_START);

        btn_example.setText("Example !");
        btn_example.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exampleActionPerformed(evt);
            }
        });
        add(btn_example, java.awt.BorderLayout.PAGE_END);

        txt_input_rtl.setColumns(20);
        txt_input_rtl.setRows(5);
        txt_input_rtl.setTabSize(3);
        txt_input_rtl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_input_rtlKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txt_input_rtl);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exampleActionPerformed
        this.setInputRTL(ex_gen.getContent());
        ex_gen.next();
    }//GEN-LAST:event_btn_exampleActionPerformed

    private void txt_input_rtlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_input_rtlKeyTyped
        // input was touched always the user type, not setText()
        if (evt.getKeyChar() != 23) {
            input_was_touched();
        }
    }//GEN-LAST:event_txt_input_rtlKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane _txt_input_rtl;
    private javax.swing.JButton btn_example;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane lbl_;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextArea txt_input_rtl;
    // End of variables declaration//GEN-END:variables

    private boolean input_changed = false;
    private final ExampleGenerator ex_gen = new ExampleGenerator();

    void setInputRTL(String text) {
        this.history.add(text);
        this.txt_input_rtl.setText(text);
        this.txt_input_rtl.setCaretPosition(0);
    }

    String getInputRTLValue() {
        return this.txt_input_rtl.getText();
    }

    boolean get_input_changed() {
        return this.input_changed;
    }

    void reset() {
        this.lbl_title.setText("<Not saved>");
        this.txt_input_rtl.setText("");
        this.input_changed = false;
        this.history.reset();
    }

    void setLblFile(String value) {
        lbl_title.setText(value);
    }

    private void input_was_touched() {
        input_changed = true;
    }

    void resetWasEdited() {
        this.input_changed = false;
    }

    void undo() {
        this.history.undo();
        this.txt_input_rtl.setText(history.get());
        this.input_changed = true;
    }

    void redo() {
        this.history.redo();
        this.txt_input_rtl.setText(history.get());
        this.input_changed = true;
    }

    void reset_history() {
        this.history.reset();
        this.history.add(this.txt_input_rtl.getText());
    }

    void on_save() {
        this.history.add(this.txt_input_rtl.getText());
    }
}
