package com.alexis.martinez.trabajo.hdltranspiler.ui;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Alexis Martinez
 */
public class PnlSystemVerilogOutput extends javax.swing.JPanel {

    /**
     * Creates new form SystemVerilog_output
     */
    public PnlSystemVerilogOutput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_copy = new javax.swing.JButton();
        jTabbedOutput = new javax.swing.JTabbedPane();
        jScrollPaneSV = new javax.swing.JScrollPane();
        txt_area_output_system_verilog = new javax.swing.JTextArea();
        jScrollPaneV = new javax.swing.JScrollPane();
        txt_area_output_converted_to_verilog = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        btn_copy.setText("Copy");
        btn_copy.setToolTipText("");
        btn_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copyActionPerformed(evt);
            }
        });
        add(btn_copy, java.awt.BorderLayout.PAGE_END);

        txt_area_output_system_verilog.setEditable(false);
        txt_area_output_system_verilog.setColumns(20);
        txt_area_output_system_verilog.setRows(5);
        txt_area_output_system_verilog.setTabSize(2);
        jScrollPaneSV.setViewportView(txt_area_output_system_verilog);

        jTabbedOutput.addTab("System verilog description", jScrollPaneSV);

        txt_area_output_converted_to_verilog.setEditable(false);
        txt_area_output_converted_to_verilog.setColumns(20);
        txt_area_output_converted_to_verilog.setRows(5);
        txt_area_output_converted_to_verilog.setTabSize(2);
        jScrollPaneV.setViewportView(txt_area_output_converted_to_verilog);

        jTabbedOutput.addTab("Verilog description", jScrollPaneV);

        add(jTabbedOutput, java.awt.BorderLayout.CENTER);
        jTabbedOutput.getAccessibleContext().setAccessibleName("SystemVerilog");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copyActionPerformed
        StringSelection stringSelection = new StringSelection("");
        if (jTabbedOutput.getSelectedIndex() == 0) {
                stringSelection = new StringSelection(this.txt_area_output_system_verilog.getText());
        } else if (jTabbedOutput.getSelectedIndex() == 1) {
                stringSelection = new StringSelection(this.txt_area_output_converted_to_verilog.getText());
        }
        
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_btn_copyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_copy;
    private javax.swing.JScrollPane jScrollPaneSV;
    private javax.swing.JScrollPane jScrollPaneV;
    private javax.swing.JTabbedPane jTabbedOutput;
    private javax.swing.JTextArea txt_area_output_converted_to_verilog;
    private javax.swing.JTextArea txt_area_output_system_verilog;
    // End of variables declaration//GEN-END:variables

    JTextArea getTextAreaOutputSV() {
        return txt_area_output_system_verilog;
    }

    JTextArea getTextAreaOutputV() {
        return txt_area_output_converted_to_verilog;
    }

    void reset() {
        txt_area_output_converted_to_verilog.setText("");
        txt_area_output_system_verilog.setText("");
    }
}
