/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.HdlTranspiler;

import java.awt.Image;

import java.io.File;
import java.io.IOException;

import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author Alexis Martinez
 */
public class TranspilerUI extends javax.swing.JFrame {

    /**
     * Creates new form TranspilerUI
     */
    public TranspilerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file_chooser = new javax.swing.JFileChooser();
        pnlGridMain1 = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlGridMain();
        javax.swing.JButton btn_convert = new javax.swing.JButton();
        menu_bar = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_open_HDL_file = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hdl to System Verilog transpiler");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage((new FlatSVGIcon("svg/icon.svg")).getImage());
        setMinimumSize(new java.awt.Dimension(600, 600));

        pnlGridMain1.setMinimumSize(new java.awt.Dimension(300, 72));
        pnlGridMain1.setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().add(pnlGridMain1, java.awt.BorderLayout.CENTER);

        btn_convert.setText("Convert to SystemVerilog");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_convert, java.awt.BorderLayout.PAGE_END);

        menu_file.setText("File");

        menu_open_HDL_file.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_open_HDL_file.setText("New .Hdl file");
        menu_open_HDL_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_open_HDL_fileActionPerformed(evt);
            }
        });
        menu_file.add(menu_open_HDL_file);

        menu_bar.add(menu_file);

        menu_edit.setText("Edit");
        menu_bar.add(menu_edit);

        setJMenuBar(menu_bar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed

        this.pnlGridMain1.pnl_output_console.txt_area_output.setText("");
        this.pnlGridMain1.pnl_system_verilog_output.txt_area_output_system_verilog.setText("");
        try {
            String input = this.pnlGridMain1.pnl_RTL_input1.input_rtl.getText();
            String transpile_out = HdlTranspiler.transpile(input);
            this.pnlGridMain1.pnl_system_verilog_output.txt_area_output_system_verilog.setText(transpile_out);
        } catch (Exception ex) {
            Logger.getLogger(TranspilerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.pnlGridMain1.pnl_output_console.txt_area_output.setText(HdlTranspiler.toStringTreeForLookingForSyntaxErrors());


    }//GEN-LAST:event_btn_convertActionPerformed

    private void menu_open_HDL_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_open_HDL_fileActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "HDL", "hdl");

        file_chooser.setFileFilter(filter);
        int returnVal = file_chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = file_chooser.getSelectedFile();

            try {

                String content = Files.readString(file.toPath());
                this.pnlGridMain1.pnl_RTL_input1.input_rtl.setText(content);
                this.pnlGridMain1.pnl_RTL_input1.input_rtl.setText(content);

            } catch (IOException ex) {
                Logger.getLogger(TranspilerUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_menu_open_HDL_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranspilerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser file_chooser;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenuItem menu_open_HDL_file;
    private com.alexis.martinez.trabajo.hdltranspiler.ui.PnlGridMain pnlGridMain1;
    // End of variables declaration//GEN-END:variables
}
