/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alexis.martinez.trabajo.hdltranspiler.ui;

import com.alexis.martinez.trabajo.hdltranspiler.sharedlibrary.HdlTranspiler;
import com.alexis.martinez.trabajo.hdltranspiler.ui.input_state.InputState;
import com.alexis.martinez.trabajo.hdltranspiler.ui.input_state.None;
import com.alexis.martinez.trabajo.hdltranspiler.ui.input_state.FileExists;

import java.io.File;
import java.io.IOException;

import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexis Martinez
 */
public class TranspilerUI extends javax.swing.JFrame {

    private File actual_file;

    /**
     * Creates new form TranspilerUI
     */
    public TranspilerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file_chooser_open = new javax.swing.JFileChooser();
        file_chooser_save = new javax.swing.JFileChooser();
        pnlGridMain1 = new com.alexis.martinez.trabajo.hdltranspiler.ui.PnlGridMain();
        javax.swing.JButton btn_convert = new javax.swing.JButton();
        menu_bar = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_new_HDL_file = new javax.swing.JMenuItem();
        menu_open_hdl = new javax.swing.JMenuItem();
        menu_save_hdl = new javax.swing.JMenuItem();
        menu_close_hdl = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();

        file_chooser_open.setToolTipText("");
        file_chooser_open.getAccessibleContext().setAccessibleParent(this);

        file_chooser_save.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        file_chooser_save.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hdl to System Verilog transpiler");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage((new FlatSVGIcon("svg/icon.svg")).getImage());
        setMinimumSize(new java.awt.Dimension(600, 600));

        pnlGridMain1.setMinimumSize(new java.awt.Dimension(300, 72));
        pnlGridMain1.setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().add(pnlGridMain1, java.awt.BorderLayout.CENTER);

        btn_convert.setText("Convert to SystemVerilog");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });
        getContentPane().add(btn_convert, java.awt.BorderLayout.PAGE_END);

        menu_file.setText("File");

        menu_new_HDL_file.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_new_HDL_file.setText("New HDL");
        menu_new_HDL_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_new_HDL_fileActionPerformed(evt);
            }
        });
        menu_file.add(menu_new_HDL_file);

        menu_open_hdl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_open_hdl.setText("Open file");
        menu_open_hdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_open_hdlActionPerformed(evt);
            }
        });
        menu_file.add(menu_open_hdl);

        menu_save_hdl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_save_hdl.setText("Save HDL");
        menu_save_hdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_save_hdlActionPerformed(evt);
            }
        });
        menu_file.add(menu_save_hdl);

        menu_close_hdl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_close_hdl.setText("Close HDL");
        menu_close_hdl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_close_hdlActionPerformed(evt);
            }
        });
        menu_file.add(menu_close_hdl);

        menu_bar.add(menu_file);

        menu_edit.setText("Edit");
        menu_bar.add(menu_edit);

        setJMenuBar(menu_bar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed

        this.pnlGridMain1.setConsoleOutput("");
        this.pnlGridMain1.setSystemVerilogOutput("");
        try {
            String input = this.pnlGridMain1.getInputRTLValue();
            String transpile_out = HdlTranspiler.transpile(input);
            this.pnlGridMain1.setSystemVerilogOutput(transpile_out);
        } catch (Exception ex) {
            Logger.getLogger(TranspilerUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.pnlGridMain1.setConsoleOutput(HdlTranspiler.toStringTreeForLookingForSyntaxErrors());


    }//GEN-LAST:event_btn_convertActionPerformed

    private void menu_new_HDL_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_new_HDL_fileActionPerformed
        int save = JOptionPane.YES_OPTION;

        if (this.pnlGridMain1.get_input_changed()) {
            save = answerUserToSaveTheirWork();

            if (save == JOptionPane.YES_OPTION) {
                menu_save_hdlActionPerformed(evt);
            }
        }
        if (save != JOptionPane.CANCEL_OPTION) {
            if (create_new_file() == JFileChooser.APPROVE_OPTION) {
                this.pnlGridMain1.reset();
                this.pnlGridMain1.setLblFile(actual_file.getName());
            }
        }
    }//GEN-LAST:event_menu_new_HDL_fileActionPerformed

    private void menu_open_hdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_open_hdlActionPerformed

        int save = JOptionPane.YES_OPTION;

        if (this.pnlGridMain1.get_input_changed()) {
            save = answerUserToSaveTheirWork();

            if (save == JOptionPane.YES_OPTION) {
                menu_save_hdlActionPerformed(evt);
            }
        }
        if (save != JOptionPane.CANCEL_OPTION) {
            open_file();
        }
    }//GEN-LAST:event_menu_open_hdlActionPerformed

    private void menu_close_hdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_close_hdlActionPerformed
        int save = JOptionPane.YES_OPTION;

        if (this.pnlGridMain1.get_input_changed()) {
            save = answerUserToSaveTheirWork();

            if (save == JOptionPane.YES_OPTION) {
                menu_save_hdlActionPerformed(evt);
            }
        }
        if (save != JOptionPane.CANCEL_OPTION) {
            this.pnlGridMain1.reset();
            is = is.close();
        }

    }//GEN-LAST:event_menu_close_hdlActionPerformed

    private void menu_save_hdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_save_hdlActionPerformed

        if (is instanceof FileExists) {
            saveFromFile(actual_file);
            this.pnlGridMain1.resetWasEdited();

        } else if (is instanceof None) {
            if (create_new_file() == JFileChooser.APPROVE_OPTION) {
                saveFromFile(actual_file);
                this.pnlGridMain1.resetWasEdited();
            }
        } else {
            throw new UnsupportedOperationException("Invalid option.");
        }

    }//GEN-LAST:event_menu_save_hdlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranspilerUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranspilerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser file_chooser_open;
    private javax.swing.JFileChooser file_chooser_save;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JMenuItem menu_close_hdl;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenuItem menu_new_HDL_file;
    private javax.swing.JMenuItem menu_open_hdl;
    private javax.swing.JMenuItem menu_save_hdl;
    private com.alexis.martinez.trabajo.hdltranspiler.ui.PnlGridMain pnlGridMain1;
    // End of variables declaration//GEN-END:variables
    private InputState is = new None();

    private void saveFromFile(File file) {
        try {
            FileWriter fw = new FileWriter(file.getAbsolutePath());
            fw.write(this.pnlGridMain1.getInputRTLValue());
            fw.close();

            is = is.new_file();

        } catch (IOException ex) {
            Logger.getLogger(TranspilerUI.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int answerUserToSaveTheirWork() {
        return JOptionPane.showConfirmDialog(
                this,
                "Do you want to save your actual file?",
                "There are changes that have not been saved",
                JOptionPane.YES_NO_CANCEL_OPTION);
    }

    private int create_new_file() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "HDL", "hdl");
        file_chooser_save.setFileFilter(filter);
        int returnVal = file_chooser_save.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.actual_file = file_chooser_save.getSelectedFile();
            is = is.new_file();
        }
        return returnVal;
    }

    private void open_file() {
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "HDL", "hdl");
        file_chooser_open.setFileFilter(filter);
        int returnVal = file_chooser_open.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            this.actual_file = file_chooser_open.getSelectedFile();

            try {
                String content = Files.readString(actual_file.toPath());
                this.pnlGridMain1.reset();
                this.pnlGridMain1.setRTLInput(content);
                this.pnlGridMain1.setLblFile(actual_file.getName());

                is = is.new_file();

            } catch (IOException ex) {
                Logger.getLogger(TranspilerUI.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

}
