package com.example.hdltranspiler.ui;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author u0_a525
 */
public class PnlSystemVerilogOutput extends javax.swing.JPanel {

    /**
     * Creates new form SystemVerilog_output
     */
    public PnlSystemVerilogOutput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_system_verilog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_output_system_verilog = new javax.swing.JTextArea();
        btn_copy = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lbl_system_verilog.setText("System Verilog description output");
        add(lbl_system_verilog, java.awt.BorderLayout.PAGE_START);

        txt_area_output_system_verilog.setEditable(false);
        txt_area_output_system_verilog.setColumns(20);
        txt_area_output_system_verilog.setRows(5);
        txt_area_output_system_verilog.setTabSize(2);
        jScrollPane1.setViewportView(txt_area_output_system_verilog);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btn_copy.setText("Copy");
        btn_copy.setToolTipText("");
        btn_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copyActionPerformed(evt);
            }
        });
        add(btn_copy, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copyActionPerformed

        StringSelection stringSelection = new StringSelection(this.txt_area_output_system_verilog.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_btn_copyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_copy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_system_verilog;
    public javax.swing.JTextArea txt_area_output_system_verilog;
    // End of variables declaration//GEN-END:variables
}
